language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install lftp
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - webpack
deploy:
  provider: script
  script:
    - lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "lcd public_html; cd ng-infinity-scroll; mrm *; mput *; bye"
  skip_cleanup: true
