language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install lftp
before_script:
  - npm install -g gulp-cli
  - npm install -g bower
script: 
  - gulp
  - webpack
deploy:
  - provider: script
    script:
      - bower register ng-infinity-scroll git@github.com:hhdevelopment/ng-infinity-scroll.git
    skip_cleanup: true
