language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install lftp
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - webpack
deploy:
  provider: script
  script:
    - lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "cd ng-infinity-scroll; mrm *; bye"
    - lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "cd public_html; put *; bye"
  skip_cleanup: true
deploy:
  provider: script
  script:
    - git config user.email "francois.achache@gmail.com"
    - git config user.name "hhfrancois"
    - npm version patch
    - git push origin --tags
  on: jkl
  skip_cleanup: true
deploy:
  provider: npm
  email: "francois.achache@gmail.com"
  api_key: "$NPM_TOKEN"
  on: jkl
  skip_cleanup: true
