language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
before_install:
  - sudo apt-get install lftp
before_script:
  - git config user.email "$GITHUB_MAIL"
  - git config user.name "$GITHUB_USER"
  - npm install -g gulp-cli
  - npm install -g bower
script: 
  - echo "Gulp"
  - gulp
  - echo "Webpack"
  - webpack
  - echo "Update package version"
  - npm version patch -m "[ci skip]"
  - git status
deploy:
  - provider: releases
    user: "$GITHUB_USER"
    api_key: "$GITHUB_TOKEN"
    file: "package.json"
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: "$NPM_MAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on: 
      branch: master
  - provider: script
    script:
      - echo "Deploy demo"
      - lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "lcd public_html; cd ng-infinity-scroll; mrm *; mput *; bye"
    skip_cleanup: true
    on: 
      branch: master
  - provider: script
    script:
      - echo "Register bower"
      - bower register ng-infinity-scroll https://github.com/hhdevelopment/ng-infinity-scroll.git
    skip_cleanup: true
    on: 
      branch: bower
