language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install lftp
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - webpack
  - ls
  - ls public_html/
after_script:
  - lftp sftp://$SFTP_1AND1_HOST -e "cd ng-infinity-scroll; mrm *; bye"
  
