language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - webpack
after_script:
    "find /public_html/ -exec curl --ftp-create-dirs -T {} -u $SFTP_1AND1_USER:$SFTP_1AND1_PWD sftp://$SFTP_1AND1_HOST/test"
